### PR TITLE
det_authority: use yoast schema graph to parse calendar

### PR DESCRIPTION
**Pull request by rhetr**
**Issue:** #23

as mentioned in the issue, the tests are not working but I'm not sure if it makes sense to update the tests when the mixin should be overhauled to use the events calendar api soon anyway.

### CODE REVIEW

**Comment by jpt-c** [comment]
I don't know the history here w/ the switch to an Events Calendar API.  So that future PRs/etc. don't crash though it'd be good to at least skip the failing tests w/ an explanatory comment.

**Comment by rhetr** [comment]
do you know why the checks are failing? not really sure what the issue is, i'm not getting any issues locally.

**Comment by jpt-c** [comment]
could you try try updating dependencies via a pipenv update on thiis branch & see if that resolves the black incompatibility issue that GitHub actions is hitting?

**Comment by rhetr** [comment]
ugh i keep running into failed checks. looks like the latest one is that `black` requires `typed_ast` but only for python3.7 (from [pypi](https://pypi.org/project/black/): "PR #2053: Black no longer relies on typed-ast for Python 3.8 and higher"). the new repos you set up seem to be checking for 3.8,3.9 and 3.10 so they are not running into this problem. can we make that change on this repo too?

**Comment by jpt-c** [comment]
Yeah, nobody on the team is using <3.8 so I see no reason to not drop testing on 3.7.

Thanks for looking at this

**Comment by rhetr** [comment]
alright, apologies in advance for the messy commits/merging. i did the following to make all the checks pass:

1. on this branch: fixed all the formatting issues
2. on this branch: updated `black` to 22.6
3. on `main`: pushed the CI workflow update
4. merged main back onto this branch to benefit from the CI workflow change
5. on this branch: updated the Pipfile to use the `city-scrapers-core` git instead of PyPI

once I pushed the CI workflow update, `main` started failing on `black` being too low version (since it was only updated in the branch). perhaps i should have submitted a separate PR for 2,3 and 5 (or just pushed those changes directly to `main`) but i didn't expect to run into so many problems lol.

**Pull request merged**
